#set page(width: 16in, height: 9in, margin: (x: 0.5in, y: 0.3in))
#set text(size: 10pt)

#align(center)[#text(size: 24pt, weight: "bold")[Full Prophage Homology Survey]]
#align(center)[#text(size: 14pt)[MASH-based Analysis of 132,393 Prophage Sequences from 26,000 E. coli Genomes]]

#grid(columns: (1fr, 1fr, 1fr, 1fr),
  align: center,
  [#text(size: 18pt, weight: "bold")[132,393]\ #text(size: 9pt)[Total Sequences]],
  [#text(size: 18pt, weight: "bold")[8,187]\ #text(size: 9pt)[Genomes]],
  [#text(size: 18pt, weight: "bold")[24.6 kb]\ #text(size: 9pt)[Mean Length]],
  [#text(size: 18pt, weight: "bold")[9,153,871]\ #text(size: 9pt)[Similar Pairs (d\<0.5)]])

#pagebreak()
#text(size: 18pt, weight: "bold")[1. Sequence Length Distribution]
#v(0.2cm)
#grid(columns: (1.5fr, 1fr), gutter: 0.3cm,
  [#image("length_distribution.png", width: 100%)],
  [#table(columns: (1fr, 1fr),
    [Metric], [Value],
    [Count], [132,393],
    [Mean], [24.6 kb],
    [Median], [21.8 kb],
    [Std Dev], [15.9 kb],
    [Min], [0.3 kb],
    [Max], [222.3 kb],
    [Q25], [11.9 kb],
    [Q75], [35.2 kb])
  ])

#pagebreak()
#text(size: 18pt, weight: "bold")[2. MASH Distance Distribution]
#v(0.2cm)
#image("distance_distribution.png", width: 100%)
#v(0.2cm)
#grid(columns: (1fr, 1fr, 1fr, 1fr), gutter: 0.2cm,
  [#table(columns: (1fr, 1fr), [Metric], [Overall],
    [Pairs], [9,153,871],
    [Mean], [0.1819],
    [Median], [0.1868],
    [Std], [0.0797])],
  [#table(columns: (1fr, 1fr), [Metric], [Within Genome],
    [Pairs], [508],
    [Mean], [0.1695],
    [Median], [0.1647],
    [Std], [0.0761])],
  [#table(columns: (1fr, 1fr), [Metric], [Between Genome],
    [Pairs], [9,153,363],
    [Mean], [0.1819],
    [Median], [0.1868],
    [Std], [0.0797])],
)

#pagebreak()
#text(size: 18pt, weight: "bold")[3. Multidimensional Scaling (MDS)]
#v(0.2cm)
#text(size: 11pt)[MDS stress: 1626006.7133]
#v(0.2cm)
#image("mds_scatter.png", width: 100%)

#pagebreak()
#text(size: 18pt, weight: "bold")[4. Hierarchical Clustering]
#v(0.2cm)
#text(size: 11pt)[Optimal number of clusters: 20]
#v(0.2cm)
#image("cluster_analysis.png", width: 100%)
#v(0.2cm)
#image("dendrogram.png", width: 100%)

#pagebreak()
#text(size: 18pt, weight: "bold")[5. Genome-Level Prophage Diversity]
#v(0.2cm)
#grid(columns: (1.5fr, 1fr), gutter: 0.3cm,
  [#image("genome_prophage_count.png", width: 100%)],
  [#table(columns: (1fr, 1fr),
    [Metric], [Value],
    [Genomes with prophages], [8,187],
    [Genomes with 2+ prophages], [1,527],
    [Max prophages/genome], [5],
    [Mean prophages/genome], [1.2])
  ])

#v(0.3cm)
#image("genome_diversity.png", width: 80%)

#pagebreak()
#text(size: 18pt, weight: "bold")[6. Summary Statistics]
#v(0.2cm)
#table(columns: (3fr, 1fr, 2fr),
  [Metric], [Value], [Notes],
  [Total sequences], [132,393], [Full prophage set],
  [Total genomes], [8,187], [From 26k E. coli genomes],
  [Mean sequence length], [24.6 kb], [Range: 0.3-222.3 kb],
  [Similar pairs (d\<0.5)], [9,153,871], [Out of ~9e+09 total pairs],
  [Mean distance (similar pairs)], [0.1819], [Only pairs with d\<0.5],
  [MDS stress], [1626006.7133], [Lower is better],
  [Number of clusters], [20], [Hierarchical clustering],
  [Genomes with 2+ prophages], [1,527], [Intra-genome diversity],
)

#v(1cm)
#align(center)[#text(size: 10pt)[Generated by MASH v2.3 + Python analysis pipeline. \
Analysis date: 2026-07-29. Sample size: 10,000 sequences for pairwise analysis.]]